from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SpecializedReportSpec:
    report_id: str
    title: str
    description: str
    family: str
    audience: str
    view_key: str
    scope: str
    period_policy: str
    currency_policy: str
    question: str
    establishes: str
    caveat: str
    section_plan: tuple[str, ...]


REPORT_SPECS = (
    SpecializedReportSpec("pm_tax_accountability", "Impuestos de Property Management", "Impuestos PM por actor y período.", "costos", "stakeholder", "pm_tax_by_actor", "FBPM", "latest_year", "separate_native", "¿Qué impuestos PM fueron pagados o aplicados por cada actor?", "Muestra importes reconocidos dentro de la población gobernada de impuestos y su fuente de cobertura.", "Los importes reconocidos no implican que hayan ingresado a caja PM ni determinan responsabilidad jurídica.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("pm_services_accountability", "Servicios de Property Management", "Servicios PM por actor y período.", "costos", "stakeholder", "pm_services_by_actor", "FBPM", "latest_year", "separate_native", "¿Qué servicios PM fueron pagados o aplicados por cada actor?", "Muestra importes reconocidos dentro de la población gobernada de servicios y su fuente de cobertura.", "Los importes reconocidos no implican que hayan ingresado a caja PM ni determinan responsabilidad jurídica.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("stakeholder_support", "Aportes aplicados a Property Management", "Aportes reconocidos por actor y período.", "stakeholders", "stakeholder", "pm_support_by_actor", "FBPM", "latest_year", "separate_native", "¿Quién aportó o aplicó recursos a PM?", "Muestra apoyo reconocido por actor y Box objetivo a partir del mart gobernado de stakeholder support.", "El apoyo no constituye por sí solo caja física, deuda jurídica ni una liquidación o neteo entre actores.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("distributions_by_recipient", "Distribuciones registradas por receptor", "Distribuciones gobernadas por receptor y período.", "distribucion", "stakeholder", "distributions_by_recipient", "FBPM", "latest_year", "separate_native", "¿Quién recibió distribuciones registradas?", "Muestra la distribución registrada por receptor dentro de la membresía gobernada de distribuciones.", "La pertenencia a este universo no prueba custodia final, derecho jurídico ni saldo neto definitivo entre actores.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("rent_by_property", "Renta por inmueble / fuente", "Renta reconocida por inmueble o ubicación de origen.", "produccion", "stakeholder", "rent_by_property", "FBPM", "latest_year", "separate_native", "¿Qué inmuebles o fuentes explican la renta reconocida?", "Muestra renta operativa gobernada agrupada por ubicación para el período y moneda seleccionados.", "No determina titularidad, derecho a frutos ni distribución jurídica de la renta.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("rent_monthly_evolution", "Evolución mensual de renta", "Serie mensual de renta reconocida durante el año de corte.", "produccion", "stakeholder", "rent_monthly_evolution", "FBPM", "latest_year_months", "separate_native", "¿Cómo evolucionó mes a mes la renta reconocida?", "Muestra la serie mensual gobernada de renta operativa en moneda nativa.", "La serie no convierte moneda ni interpreta por sí sola vacancia, cobrabilidad o derechos sobre los frutos.", ("summary", "bars", "table", "method")),
    SpecializedReportSpec("opex_by_category", "Costos operativos por categoría", "OPEX de propiedad agrupado por categoría gobernada.", "costos", "stakeholder", "opex_by_category", "FBPM", "latest_year", "separate_native", "¿En qué categorías se concentraron los costos operativos de propiedad?", "Muestra OPEX reconocido por categoría semántica gobernada y moneda.", "No asigna responsabilidad jurídica por el costo ni transforma funding, deuda o distribuciones en OPEX.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("taxes_by_property", "Impuestos por inmueble", "Impuestos reconocidos agrupados por inmueble o ubicación.", "costos", "stakeholder", "taxes_by_property", "FBPM", "latest_year", "separate_native", "¿Qué inmuebles explican los impuestos reconocidos?", "Muestra impuestos de propiedad reconocidos y agrupados por ubicación.", "No determina quién debía soportarlos jurídicamente ni implica que cada pago haya pasado por caja del Box.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("services_by_property", "Servicios por inmueble", "Servicios reconocidos agrupados por inmueble o ubicación.", "costos", "stakeholder", "services_by_property", "FBPM", "latest_year", "separate_native", "¿Qué inmuebles explican los servicios reconocidos?", "Muestra servicios de propiedad reconocidos y agrupados por ubicación.", "No determina quién debía soportarlos jurídicamente ni implica que cada pago haya pasado por caja del Box.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("distributions_vs_rent", "Distribuciones y renta reconocida", "Comparación anual entre renta reconocida y distribuciones registradas.", "distribucion", "stakeholder", "distributions_vs_rent", "FBPM", "latest_year", "separate_native", "¿Cómo se comparan la renta reconocida y las distribuciones registradas del período?", "Presenta ambas magnitudes gobernadas lado a lado para facilitar la lectura administrativa.", "No supone que toda distribución provenga de la renta del mismo período ni constituye una liquidación jurídica o saldo final por actor.", ("comparison", "table", "method")),

    SpecializedReportSpec("support_by_target_box", "Apoyo reconocido por Box objetivo", "Apoyo de stakeholders agrupado por Box objetivo.", "stakeholders", "stakeholder", "support_by_target_box", "FBPM", "latest_year", "separate_native", "¿A qué Box se aplicó el apoyo reconocido de stakeholders?", "Muestra apoyo gobernado agrupado por Box objetivo dentro del scope FBPM.", "No representa por sí solo entrada física de caja, deuda jurídica ni derecho económico final entre actores.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("prior_period_clearing", "Regularizaciones de períodos anteriores", "Aplicaciones reconocidas como clearing de obligaciones de períodos anteriores.", "stakeholders", "stakeholder", "prior_period_clearing", "FBPM", "latest_year", "separate_native", "¿Qué apoyos o aplicaciones reconocidas corresponden a obligaciones de períodos anteriores?", "Muestra únicamente casos gobernados con settlement_nature=prior_period_clearing y conserva período de obligación y período de aplicación.", "La clasificación contable de clearing no prueba extinción jurídica de una deuda ni identifica por sí sola al obligado legal final.", ("summary", "table", "method")),
    SpecializedReportSpec("physical_inflows_by_box", "Entradas físicas por Box", "Entradas físicas gobernadas agrupadas por Box.", "tesoreria", "stakeholder", "physical_inflows_by_box", "FBPM", "latest_year", "separate_native", "¿Qué entradas físicas registró cada Box?", "Muestra total_cash_in del mart gobernado de rendición de tesorería, agregado por Box y moneda.", "No incluye apoyos constructivos sin paso físico por caja y no equivale a saldo de caja validado.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("physical_outflows_by_box", "Salidas físicas por Box", "Salidas físicas gobernadas agrupadas por Box.", "tesoreria", "stakeholder", "physical_outflows_by_box", "FBPM", "latest_year", "separate_native", "¿Qué salidas físicas registró cada Box?", "Muestra total_cash_out del mart gobernado de rendición de tesorería, agregado por Box y moneda.", "No transforma pagos directos de terceros en salidas físicas del Box ni demuestra custodia final de fondos.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("accountability_balance", "Balance de rendición del ciclo vigente", "Componentes del balance de rendición del ciclo más reciente de Family Business.", "tesoreria", "controller", "accountability_balance", "Family Business", "latest_year", "separate_native", "¿Cómo se forma el balance de rendición del ciclo vigente?", "Presenta saldo inicial, ingresos sujetos a rendición, distribuciones, usos respaldados, transferencias y saldo final del ciclo gobernado más reciente.", "El saldo de rendición es un control contable; no es una afirmación de caja física disponible, faltante jurídico ni apropiación de fondos.", ("table", "method")),
    SpecializedReportSpec("accountability_cycles", "Ciclos de rendición Mar–Ago / Sep–Feb", "Cierres gobernados de los ciclos semestrales de rendición de Family Business.", "tesoreria", "controller", "accountability_cycles", "Family Business", "latest_year", "separate_native", "¿Cómo cerraron los ciclos semestrales de rendición?", "Muestra una posición de cierre por ciclo gobernado Mar–Ago o Sep–Feb, preservando moneda, estado del ciclo y disponibilidad de caja validada.", "La magnitud de cierre no debe interpretarse como efectivo disponible ni como deuda jurídica automática.", ("bars", "table", "method")),
    SpecializedReportSpec("open_debt_positions", "Posiciones de deuda abiertas", "Saldos de deuda abiertos en la última posición gobernada.", "deuda", "controller", "open_debt_positions", "FBPM", "latest_year", "separate_native", "¿Qué relaciones de deuda permanecen abiertas al último cierre?", "Muestra únicamente component=total con posición disponible y saldo abierto positivo en el último período gobernado.", "La relación contable registrada no determina por sí sola legitimación, acreedor o deudor jurídico ni condiciones de exigibilidad.", ("summary", "bars", "table", "method")),
    SpecializedReportSpec("debt_activity", "Actividad de deuda", "Altas, intereses, repagos y ajustes de deuda por relación.", "deuda", "controller", "debt_activity", "FBPM", "latest_year", "separate_native", "¿Qué movimientos explicaron la actividad de deuda del período?", "Muestra flujos gobernados de nuevas obligaciones, intereses, repagos y ajustes por relación sin sumar stocks mensuales.", "Las magnitudes de actividad no constituyen un neteo jurídico y los ajustes conservan explícita su dirección sobre la deuda.", ("bars", "table", "method")),
    SpecializedReportSpec("repayment_allocations", "Asignación de repagos de deuda", "Trazabilidad de cada repago hacia las obligaciones a las que fue asignado.", "deuda", "controller", "repayment_allocations", "FBPM", "latest_year", "separate_native", "¿A qué obligaciones se aplicó cada repago registrado?", "Muestra allocated_amount a grano de asignación y conserva relación, fecha, tipo de obligación, estado y remanente del evento de repago.", "La asignación contable no determina por sí sola validez, exigibilidad o efecto jurídico del pago sobre una obligación controvertida.", ("summary", "table", "method")),

    SpecializedReportSpec("opex_monthly_evolution", "Evolución mensual de costos operativos", "Serie mensual del OPEX de propiedad reconocido.", "costos", "stakeholder", "opex_monthly_evolution", "FBPM", "latest_year_months", "separate_native", "¿Cómo evolucionaron mes a mes los costos operativos de propiedad?", "Muestra el OPEX mensual gobernado y lo reconcilia con el total anual de OPEX de propiedad.", "La evolución de costos no asigna responsabilidad jurídica ni convierte ausencia o concentración temporal en una conclusión sobre administración.", ("summary", "bars", "table", "method")),
    SpecializedReportSpec("maintenance_by_property", "Mantenimiento y conservación por inmueble", "Mantenimiento reconocido agrupado por inmueble o ubicación.", "costos", "stakeholder", "maintenance_by_property", "FBPM", "latest_year", "separate_native", "¿En qué inmuebles se concentraron los gastos de mantenimiento y conservación?", "Muestra mantenimiento reconocido por ubicación y reconcilia el total con la categoría anual gobernada.", "La ubicación es una dimensión descriptiva del gasto; no determina titularidad, obligación legal de conservación ni responsabilidad personal.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("legal_costs_by_property", "Gastos legales por inmueble / referencia", "Gastos legales reconocidos agrupados por ubicación descriptiva.", "costos", "management", "legal_costs_by_property", "FBPM", "latest_year", "separate_native", "¿A qué inmuebles o referencias se asociaron los gastos legales reconocidos?", "Muestra gastos legales ya clasificados como OPEX de propiedad y agrupados por la ubicación registrada.", "No determina estrategia jurídica, mérito de una controversia, beneficiario legal ni quién debía soportar el costo.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("support_by_obligation_category", "Apoyo reconocido por tipo de obligación", "Apoyo de stakeholders agrupado por categoría de obligación.", "stakeholders", "stakeholder", "support_by_obligation_category", "FBPM", "latest_year", "separate_native", "¿Qué tipos de obligaciones fueron sostenidos con apoyo reconocido de stakeholders?", "Agrupa recognized_amount por obligation_category dentro del mart gobernado de stakeholder support.", "La categoría de obligación no establece quién era el obligado jurídico ni convierte apoyo en caja física o deuda exigible.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("support_by_funding_channel", "Apoyo reconocido por canal", "Apoyo de stakeholders agrupado por canal de funding registrado.", "stakeholders", "management", "support_by_funding_channel", "FBPM", "latest_year", "separate_native", "¿Por qué canales contables se reconoció el apoyo de stakeholders?", "Agrupa recognized_amount por funding_channel sin reconstruir una ruta de caja distinta de la ya gobernada.", "Un canal contable no prueba por sí solo transferencia bancaria, origen jurídico del dinero ni derecho de reembolso.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("support_by_settlement_nature", "Apoyo por naturaleza de aplicación", "Apoyo reconocido agrupado por settlement_nature.", "stakeholders", "management", "support_by_settlement_nature", "FBPM", "latest_year", "separate_native", "¿Qué naturaleza administrativa tuvieron las aplicaciones de apoyo reconocidas?", "Agrupa recognized_amount por la settlement_nature ya gobernada, incluyendo clearing sólo cuando la fuente lo declara explícitamente.", "La naturaleza contable de una aplicación no determina extinción, novación, responsabilidad o efecto jurídico de una obligación.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("physical_inflows_by_category", "Entradas físicas por categoría", "Composición de entradas físicas gobernadas por categoría de caja.", "tesoreria", "stakeholder", "physical_inflows_by_category", "FBPM", "latest_year", "separate_native", "¿Qué conceptos explican las entradas físicas registradas?", "Agrupa sólo movement_basis=actual_cash por cash_category y reconcilia con total_cash_in del mart de rendición.", "No incluye apoyo constructivo sin paso físico por Box y no convierte una categoría de caja en ingreso económico.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("physical_outflows_by_category", "Salidas físicas por categoría", "Composición de salidas físicas gobernadas por categoría de caja.", "tesoreria", "stakeholder", "physical_outflows_by_category", "FBPM", "latest_year", "separate_native", "¿Qué conceptos explican las salidas físicas registradas?", "Agrupa sólo movement_basis=actual_cash por cash_category y reconcilia con total_cash_out del mart de rendición.", "No incorpora pagos directos de terceros como salidas del Box ni transforma una salida física en responsabilidad jurídica.", ("summary", "pie", "table", "method")),
    SpecializedReportSpec("cash_residuals", "Residuales de caja para revisión", "Otras entradas/salidas y movimientos físicos aún sin clasificación semántica específica.", "control", "controller", "cash_residuals", "FBPM", "latest_year", "separate_native", "¿Qué magnitudes físicas permanecen en categorías residuales de tesorería?", "Muestra other_cash_* y unknown_cash_* ya expuestos por el mart de rendición, sin re-clasificarlos en el informe.", "Un residual es una señal de control o clasificación pendiente; no demuestra error, irregularidad, deuda, faltante ni apropiación.", ("summary", "pie", "table", "method")),
)
